development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mis438
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
 
test:
  adapter: mysql
  encoding: utf8
  database: mis438
  username: root
  password: root
  host: localhost
 
production:
  adapter: mysql
  encoding: utf8
  database: mis438
  username: root
  password: root
  host: localhost
