development:
  adapter: mysql
  encoding: utf8
  database: mis438
  username: root
  password: root
  host: localhost
 
test:
  adapter: mysql
  encoding: utf8
  database: mis438
  username: root
  password: root
  host: localhost
 
production:
  adapter: mysql
  encoding: utf8
  database: mis438
  username: root
  password: root
  host: localhost
